### ISSUE TITLE
Beware of hash-URIs

### ISSUE THREAD

**Issue by betehess** [pchampin/ld-patch-testsuite#1]
Let's take

```
<#updatelist> rdf:type :PositiveEvaluationTest ;
   mf:name      "updatelist" ;
   rdfs:comment "UpdateList" ;
   mf:action [
     :data  <spec_example4.ttl> ;
     :patch <updatelist.ldpatch> 
   ];
   mf:result <updatelist.ttl>
   .
```

`<#>` in `spec_example4.ttl` is not the same than `<#>` in `updatelist.ldpatch`. Therefore this test should result in an error.

Or we need a way to say that the base URI for the patch is the one from data. Same for the result.

**Comment by pchampin** [comment]
Ehr, I think `<#>` _is_ the same in the target and the patch, according to the [specification](https://dvcs.w3.org/hg/ldpwg/raw-file/ldpatch/ldpatch.html#nodes-and-triples-semantics): 

> The base IRI used to resolve relative IRIs is the target IRI.

**Comment by betehess** [comment]
Ok. And I see that some of the tests have a custom URI.
